[actions]
PrimaryTap = { description = "Primary tap/click", kind = "Binary" }
MetaballIsoDec = { description = "Decrease metaball iso", kind = "Binary" }
MetaballIsoInc = { description = "Increase metaball iso", kind = "Binary" }
ToggleOverlay = { description = "Toggle overlay", kind = "Binary" }
DebugMode1 = { description = "Debug mode 1", kind = "Binary" }
DebugMode2 = { description = "Debug mode 2", kind = "Binary" }
DebugMode3 = { description = "Debug mode 3", kind = "Binary" }
DebugMode4 = { description = "Debug mode 4", kind = "Binary" }

[bindings]
PrimaryTap = ["Mouse:Left", "Touch:Tap"]
MetaballIsoDec = ["Key:BracketLeft"]
MetaballIsoInc = ["Key:BracketRight"]

[debug.bindings]
ToggleOverlay = ["Key:F1"]
DebugMode1 = ["Key:Digit1"]
DebugMode2 = ["Key:Digit2"]
DebugMode3 = ["Key:Digit3"]
DebugMode4 = ["Key:Digit4"]

[[virtual_axes]]
name = "MoveX"
pos = "Key:D"
neg = "Key:A"
scale = 1.0

[gesture]
tap_max_time = 0.25
tap_max_move = 12.0
# Drag-related gesture settings retained for now (can be pruned later if unused)
drag_min_move = 4.0
drag_smoothing = 0.15
