[workspace]
members = [
    "crates/metaball_renderer",
    # New core/game crates
    "crates/game_core",
    "crates/game",
    # Demos
    "demos/metaballs_test",
    "demos/gameboard_test",
    "demos/architecture_test",
]
exclude = [
    "external/bevy"
]
resolver = "2"

# Centralized dependency versions (Sprint 1 workspace-level dependencies)
[workspace.dependencies]
bevy = { version = "0.16.1", features = ["bevy_winit"] }
serde = { version = "1.0", features = ["derive"] }

[workspace.package]
edition = "2021"

