[package]
name = "ball_matcher"
version = "0.1.0"
edition = "2021"
authors = ["Adam <you@example.com>"]
license = "GPL-3.0-or-later"

[dependencies]
bevy = "0.16" # upgraded from 0.14 -> 0.16
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
ron = "0.8"
bevy_rapier2d = { version = "0.31", features = ["simd-stable", "debug-render-2d"] }
bytemuck = { version = "1.15", features = ["derive"] }
half = "2"
smallvec = "1.13"
toml = "0.8"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
getrandom = { version = "0.3", features = ["wasm_js"] }
uuid = { version = "1", features = ["js"] }

[dependencies.wgpu]
version = "26.0.1"
default-features = false
webgpu = ["bevy_internal/webgpu"]


[dev-dependencies]
tempfile = "3"

[profile.dev]
opt-level = 1

[profile.release]
codegen-units = 1
lto = "thin"
strip = true
opt-level = "z"

[features]
default = ["debug"]
# Enable with: cargo run --features debug
debug = []
# Verbose fluid simulation pass logging
fluid_debug_passes = []
