[package]
name = "bm_config"
version = "0.0.0"
edition = "2021"
license = "GPL-3.0-or-later"
publish = false

[dependencies]
serde = { workspace = true }
ron = { workspace = true }

[dev-dependencies]
tempfile = "3"

[features]
default = []
