[package]
name = "ui_demo"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
publish = false
description = "POC demo exploring Bevy-HUI with mock compositor interface"

[dependencies]
bevy = { workspace = true }
bevy_hui = "0.4"
rand = "0.8"
