[package]
name = "physics_playground"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bevy_rapier2d = { workspace = true }
rand = "0.8"

# Internal crates
game_core = { path = "../../crates/game_core" }
game_physics = { path = "../../crates/game_physics" }
metaball_renderer = { path = "../../crates/metaball_renderer" }
widget_renderer = { path = "../../crates/widget_renderer" }
game_rendering = { path = "../../crates/game_rendering" }
event_core = { path = "../../crates/event_core" }

# All previous compile-time feature flags (event_core_integration, no-compositor) have been
# collapsed. The playground always integrates Event Core and the compositor pipeline now
# for simplicity and clearer examples.
