[package]
name = "physics_playground"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bevy_rapier2d = { workspace = true }
bevy_egui = { workspace = true }
rand = "0.8"

# Internal crates
game_core = { path = "../../crates/game_core" }
game_physics = { path = "../../crates/game_physics" }
metaball_renderer = { path = "../../crates/metaball_renderer", optional = true }

[features]
default = []
with_metaballs = ["metaball_renderer"]
