[target.wasm32-unknown-unknown]
rustflags = [
  "--cfg=getrandom_backend=\"wasm_js\"",
  "-C", "target-feature=+simd128"
]
# Use wasm-server-runner so `cargo run --target wasm32-unknown-unknown` serves automatically (WebGPU only)
runner = "wasm-server-runner"

[alias]
# Aggregate local CI style checks; usage: cargo ci
ci = "fmt --all -- --check && clippy --all-targets --all-features -- -D warnings && test --all --all-features --no-fail-fast"
# WASM (WebGPU) helper aliases
wasm-build = "build --target wasm32-unknown-unknown"
wasm-build-release = "build --target wasm32-unknown-unknown --release"
wasm-run = "run --target wasm32-unknown-unknown"
wasm-run-release = "run --target wasm32-unknown-unknown --release"
wasm-serve = "run --target wasm32-unknown-unknown"
wasm-serve-release = "run --target wasm32-unknown-unknown --release"
