name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    name: Format / Clippy / Test / Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          rustup toolchain install stable --profile minimal
          rustup default stable

      - name: Cache cargo (dependencies)
        uses: Swatinem/rust-cache@v2

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Clippy (deny warnings)
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build
        run: cargo build --all-targets --all-features

      - name: Test
        run: cargo test --all --all-features --no-fail-fast

  wasm:
    name: WASM build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust + wasm target
        run: |
          rustup toolchain install stable --profile minimal
          rustup default stable
          rustup target add wasm32-unknown-unknown

      - name: Cache cargo (dependencies)
        uses: Swatinem/rust-cache@v2

      - name: Build (wasm release)
        env:
          RUSTFLAGS: '-C target-feature=+simd128 --cfg=getrandom_backend="wasm_js"'
        run: cargo build --release --target wasm32-unknown-unknown
