[package]
name = "input_demo"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
publish = false

[dependencies]
bevy = { workspace = true }
# Core event/input pipeline
event_core = { path = "../../crates/event_core" }

# (Optional) for randomness if future experiments need it
rand = "0.8"
