[package]
name = "bm_core"
version = "0.0.0"
edition = "2021"
license = "GPL-3.0-or-later"
publish = false

[dependencies]
bevy = { workspace = true }
bm_config = { path = "../config" }

[features]
default = []
